# This is a basic workflow to help you get started with Actions

name: Lint HTML Code Base

# Controls when the workflow will run
on:
  # Triggers the workflow on push to dev branches
  push:
    branches-ignore:
      - main
      - js-docs 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-tests:
    name: HTML Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Run HTML Linters automatically
      - name: Run HTML Style and Format Linters 
        run: | 
              npm i # Handle installation on virtual machine
              npm run html_style_lint # Run linter tests and output results
              npm run html_format_lint # Run linter tests and output results
   
   
