# This is a basic workflow to help you get started with Actions

name: Lint Code Base

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches-ignore:
      - main
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-tests:
    name: Lint Code Base Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Run Jest and Cypress to automatically run tests and show code coverage
      - name: Run StyleLint
        run: | 
              npm i # Handle installation on virtual machine
              npm run css_lint_test # Run linter tests and output results
      - name: Run ESlint
        run: |
              npm i
              npm run js_lint_test # Run linter tests for javascript
   
   
