# This is a basic workflow to help you get started with Actions

name: Lint Code Base

# Controls when the workflow will run
on:
  # Triggers the workflow on push to dev branches
  push:
    branches-ignore:
      - main
      - js-docs 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-tests:
    name: HTML Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Run JS, CSS, and HTML Style/Format Linters
      - name: Run EsLint, StyleLint, & HTML Lint
        run: | 
              npm i # Handle installation on virtual machine
              npm run js_lint_test # Run linter tests for javascript
              npm run css_lint_test # Run linter tests and output results
              npm run html_style_lint # Run HTML style linter tests and output results
              npm run html_format_lint # Run HTML format linter tests and output results
   
   
